### ISSUE TITLE
Release a gem

### ISSUE THREAD

**Issue by zedtux** [invzn/tabularasa#3]
When [latest issue](https://github.com/callenrosario/tabularasa/issues/1) will be closed, could you release a gem on Rubygem.org ?

**Comment by zedtux** [comment]
Oops... sorry. I'm tired... I said that because I didn't see any .gemspec file in your git repo...

But it should be done: Because in that case, we will be able to use bundler pointing to your github.com repo.

**Comment by invzn** [comment]
No problem, I forgot to push last night. Thanks for the reminder. I just pushed the new changes.
